language: node_js
sudo: false
node_js:
  - 8
services:
  - redis-server
  - mongodb  
script:
  - npm run coverage
after_success:
  - npm run publish-coverage
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
      - libzmq3-dev
before_install:
  - sleep 5
